### ISSUE TITLE
如何响应按钮点击事件

### ISSUE THREAD

**Issue by m986883511** [CrystalWindSnake/nicegui-toolkit#40]
![image](https://github.com/user-attachments/assets/67cae243-5958-40b5-a14f-4c108b146c3f)

这个项目 https://github.com/Bamdad-rar/NiceguiSimpleAdminPanel

**Comment by CrystalWindSnake** [comment]
@m986883511 目前 toolkit 会拦截页面上大部分的点击事件。你是希望在界面设计阶段可以点击按钮，以便执行一些功能？后面可以考虑增设一个开关，让使用者可以随时切换是否拦截点击事件

**Comment by m986883511** [comment]
好主意的，那我关闭了
